# Generated by Django 4.1.4 on 2023-01-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="image",
            field=models.ImageField(
                blank=True, default="uploads/car.png", null=True, upload_to="uploads/"
            ),
        ),
    ]
