# Generated by Django 4.1.4 on 2023-01-03 08:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TopicSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(
                        null=True, unique=True, verbose_name="Topic series"
                    ),
                ),
                (
                    "published",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date published"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": ("Topic series",),
                "ordering": ["-published"],
            },
        ),
        migrations.CreateModel(
            name="Topics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("subtitle", models.CharField(blank=True, default="", max_length=255)),
                ("speaker", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("topicSlug", models.SlugField(unique=True, verbose_name="Topic slug")),
                (
                    "published",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date published"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date modified"
                    ),
                ),
                (
                    "series",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        to="home.topicseries",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": ("Topics",),
                "ordering": ["-published"],
            },
        ),
    ]
