# Generated by Django 4.1.4 on 2023-01-03 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="topics",
            options={"ordering": ["-published"], "verbose_name_plural": "TOPICS"},
        ),
        migrations.AlterModelOptions(
            name="topicseries",
            options={"ordering": ["-published"], "verbose_name_plural": "SERIES"},
        ),
    ]
