# Generated by Django 4.1.4 on 2023-01-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_topics_image_alter_topicseries_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="image",
            field=models.ImageField(default="uploads/car.png", upload_to="uploads/"),
        ),
        migrations.AlterField(
            model_name="topicseries",
            name="image",
            field=models.ImageField(default="uploads/car.png", upload_to="uploads/"),
        ),
    ]
