# Generated by Django 4.1.4 on 2023-01-03 11:33

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_topics_options_alter_topicseries_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="content",
            field=tinymce.models.HTMLField(blank=True, default=""),
        ),
    ]
