# Generated by Django 4.1.4 on 2023-01-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alter_topics_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topics",
            old_name="topicSlug",
            new_name="topic_slug",
        ),
    ]
