# Generated by Django 4.1.4 on 2023-01-04 08:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_topics_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicseries",
            name="image",
            field=models.ImageField(
                default="default/car.png",
                max_length=255,
                upload_to=home.models.TopicSeries.image_upload_to,
            ),
        ),
    ]
