# Generated by Django 4.1.4 on 2023-01-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0010_alter_topics_image_alter_topicseries_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicseries",
            name="series_id",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
