# Generated by Django 4.1.4 on 2023-01-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_remove_topicseries_series_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topics",
            name="series",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="home.topicseries",
            ),
        ),
    ]
